-- Phase 17B: Cluster governance tables.
--
-- cluster_membership_history captures every membership mutation performed by
-- the governance layer (merge / split / move / recluster / review accept).
-- Every governance write must record at least one row here so the change can
-- be audited and replayed. The V1/V2 assignment strategies do NOT write this
-- table — they keep using hot_cluster_item.assigned_at / removed_at.
--
-- cluster_review_task materializes REVIEW_REQUIRED cluster_match_decision
-- rows into a state machine (OPEN -> ACCEPTED / REJECTED / SKIPPED). The
-- decision_id is unique so a single decision can never spawn two tasks.

CREATE TABLE cluster_membership_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_cluster_id BIGINT NOT NULL,
    hot_item_id BIGINT NOT NULL,
    action VARCHAR(16) NOT NULL,
    from_cluster_id BIGINT,
    to_cluster_id BIGINT,
    reason TEXT NOT NULL,
    operator_type VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    operator_id VARCHAR(128),
    related_decision_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cluster_membership_history_cluster
        FOREIGN KEY (hot_cluster_id) REFERENCES hot_cluster (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cluster_membership_history_item
        FOREIGN KEY (hot_item_id) REFERENCES hot_item (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cluster_membership_history_from_cluster
        FOREIGN KEY (from_cluster_id) REFERENCES hot_cluster (id) ON DELETE SET NULL,
    CONSTRAINT fk_cluster_membership_history_to_cluster
        FOREIGN KEY (to_cluster_id) REFERENCES hot_cluster (id) ON DELETE SET NULL,
    CONSTRAINT ck_cluster_membership_history_action
        CHECK (action IN ('ADD', 'REMOVE', 'MOVE', 'MERGE', 'SPLIT', 'RECLUSTER')),
    CONSTRAINT ck_cluster_membership_history_operator
        CHECK (operator_type IN ('SYSTEM', 'MANUAL'))
);

CREATE INDEX idx_cluster_membership_history_cluster_created
    ON cluster_membership_history (hot_cluster_id, created_at DESC);

CREATE INDEX idx_cluster_membership_history_item_created
    ON cluster_membership_history (hot_item_id, created_at DESC);

CREATE INDEX idx_cluster_membership_history_action_created
    ON cluster_membership_history (action, created_at DESC);

CREATE TABLE cluster_review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_match_decision_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    resolution_reason TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cluster_review_task_decision
        FOREIGN KEY (cluster_match_decision_id) REFERENCES cluster_match_decision (id) ON DELETE RESTRICT,
    CONSTRAINT ck_cluster_review_task_status
        CHECK (status IN ('OPEN', 'ACCEPTED', 'REJECTED', 'SKIPPED')),
    CONSTRAINT ck_cluster_review_task_resolution
        CHECK ((status = 'OPEN' AND resolution_reason IS NULL)
               OR (status <> 'OPEN' AND resolution_reason IS NOT NULL))
);

CREATE UNIQUE INDEX uq_cluster_review_task_decision
    ON cluster_review_task (cluster_match_decision_id);

CREATE INDEX idx_cluster_review_task_status_created
    ON cluster_review_task (status, created_at DESC);
