CREATE TABLE source_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    crawl_interval_minutes INTEGER,
    config_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_source_config_source_code UNIQUE (source_code),
    CONSTRAINT ck_source_config_interval
        CHECK (crawl_interval_minutes IS NULL OR crawl_interval_minutes > 0),
    CONSTRAINT ck_source_config_payload_object
        CHECK (jsonb_typeof(config_payload) = 'object')
);

CREATE INDEX idx_source_config_type_enabled
    ON source_config (source_type, enabled);

CREATE TABLE crawl_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_config_id BIGINT NOT NULL,
    trigger_type VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    idempotency_key VARCHAR(128),
    retry_of_task_id BIGINT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    persisted_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    failure_code VARCHAR(64),
    failure_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crawl_task_source_config
        FOREIGN KEY (source_config_id) REFERENCES source_config (id) ON DELETE RESTRICT,
    CONSTRAINT fk_crawl_task_retry_of
        FOREIGN KEY (retry_of_task_id) REFERENCES crawl_task (id) ON DELETE SET NULL,
    CONSTRAINT ck_crawl_task_trigger_type
        CHECK (trigger_type IN ('MANUAL', 'SCHEDULED', 'RETRY')),
    CONSTRAINT ck_crawl_task_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL_FAILED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_crawl_task_counts
        CHECK (fetched_count >= 0 AND persisted_count >= 0 AND failed_count >= 0),
    CONSTRAINT ck_crawl_task_time_order
        CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE UNIQUE INDEX uq_crawl_task_idempotency_key
    ON crawl_task (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_crawl_task_source_requested
    ON crawl_task (source_config_id, requested_at DESC);

CREATE INDEX idx_crawl_task_status_requested
    ON crawl_task (status, requested_at DESC);

CREATE TABLE raw_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_task_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    source_url TEXT,
    raw_payload JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    published_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_raw_item_crawl_task
        FOREIGN KEY (crawl_task_id) REFERENCES crawl_task (id) ON DELETE RESTRICT,
    CONSTRAINT uq_raw_item_task_source_external
        UNIQUE (crawl_task_id, source_type, external_id)
);

CREATE INDEX idx_raw_item_source_external
    ON raw_item (source_type, external_id);

CREATE INDEX idx_raw_item_fetched_at
    ON raw_item (fetched_at DESC);

CREATE INDEX idx_raw_item_payload_gin
    ON raw_item USING GIN (raw_payload);

CREATE TABLE hot_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latest_raw_item_id BIGINT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    source_url TEXT NOT NULL,
    author VARCHAR(255),
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    metrics JSONB NOT NULL DEFAULT '{}'::JSONB,
    content_hash CHAR(64) NOT NULL,
    published_at TIMESTAMPTZ,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hot_item_latest_raw_item
        FOREIGN KEY (latest_raw_item_id) REFERENCES raw_item (id) ON DELETE RESTRICT,
    CONSTRAINT uq_hot_item_source_external
        UNIQUE (source_type, external_id),
    CONSTRAINT ck_hot_item_tags_array
        CHECK (jsonb_typeof(tags) = 'array'),
    CONSTRAINT ck_hot_item_metrics_object
        CHECK (jsonb_typeof(metrics) = 'object'),
    CONSTRAINT ck_hot_item_seen_time_order
        CHECK (last_seen_at >= first_seen_at)
);

CREATE INDEX idx_hot_item_published_at
    ON hot_item (published_at DESC);

CREATE INDEX idx_hot_item_tags_gin
    ON hot_item USING GIN (tags);

CREATE TABLE hot_cluster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    primary_item_id BIGINT,
    merged_into_cluster_id BIGINT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hot_cluster_primary_item
        FOREIGN KEY (primary_item_id) REFERENCES hot_item (id) ON DELETE SET NULL,
    CONSTRAINT fk_hot_cluster_merged_into
        FOREIGN KEY (merged_into_cluster_id) REFERENCES hot_cluster (id) ON DELETE SET NULL,
    CONSTRAINT ck_hot_cluster_status
        CHECK (status IN ('ACTIVE', 'MERGED', 'ARCHIVED')),
    CONSTRAINT ck_hot_cluster_seen_time_order
        CHECK (last_seen_at >= first_seen_at),
    CONSTRAINT ck_hot_cluster_not_merged_into_self
        CHECK (merged_into_cluster_id IS NULL OR merged_into_cluster_id <> id),
    CONSTRAINT ck_hot_cluster_merge_target
        CHECK (
            (status = 'MERGED' AND merged_into_cluster_id IS NOT NULL)
            OR (status <> 'MERGED' AND merged_into_cluster_id IS NULL)
        )
);

CREATE INDEX idx_hot_cluster_status_last_seen
    ON hot_cluster (status, last_seen_at DESC);

CREATE TABLE hot_cluster_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_cluster_id BIGINT NOT NULL,
    hot_item_id BIGINT NOT NULL,
    match_method VARCHAR(32) NOT NULL,
    match_score NUMERIC(6, 5),
    match_reason JSONB NOT NULL DEFAULT '{}'::JSONB,
    rule_version VARCHAR(64) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMPTZ,
    CONSTRAINT fk_hot_cluster_item_cluster
        FOREIGN KEY (hot_cluster_id) REFERENCES hot_cluster (id) ON DELETE RESTRICT,
    CONSTRAINT fk_hot_cluster_item_item
        FOREIGN KEY (hot_item_id) REFERENCES hot_item (id) ON DELETE RESTRICT,
    CONSTRAINT ck_hot_cluster_item_score
        CHECK (match_score IS NULL OR (match_score >= 0 AND match_score <= 1)),
    CONSTRAINT ck_hot_cluster_item_reason_object
        CHECK (jsonb_typeof(match_reason) = 'object'),
    CONSTRAINT ck_hot_cluster_item_time_order
        CHECK (removed_at IS NULL OR removed_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_hot_cluster_item_active_membership
    ON hot_cluster_item (hot_item_id)
    WHERE removed_at IS NULL;

CREATE UNIQUE INDEX uq_hot_cluster_item_one_active_primary
    ON hot_cluster_item (hot_cluster_id)
    WHERE removed_at IS NULL AND is_primary;

CREATE INDEX idx_hot_cluster_item_active_cluster
    ON hot_cluster_item (hot_cluster_id, assigned_at)
    WHERE removed_at IS NULL;

CREATE TABLE hot_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_cluster_id BIGINT NOT NULL,
    total_score NUMERIC(12, 4) NOT NULL,
    score_components JSONB NOT NULL,
    scoring_version VARCHAR(64) NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hot_score_cluster
        FOREIGN KEY (hot_cluster_id) REFERENCES hot_cluster (id) ON DELETE RESTRICT,
    CONSTRAINT ck_hot_score_total
        CHECK (total_score >= 0),
    CONSTRAINT ck_hot_score_components_object
        CHECK (jsonb_typeof(score_components) = 'object')
);

CREATE INDEX idx_hot_score_cluster_calculated
    ON hot_score (hot_cluster_id, calculated_at DESC);

CREATE INDEX idx_hot_score_ranking
    ON hot_score (total_score DESC, calculated_at DESC);
