ALTER TABLE crawl_task
    ADD COLUMN matched_count INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_crawl_task_matched_count CHECK (matched_count >= 0);

DROP INDEX uq_crawl_task_idempotency_key;

CREATE UNIQUE INDEX uq_crawl_task_source_idempotency_key
    ON crawl_task (source_config_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE crawl_task_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_task_id BIGINT NOT NULL,
    stage VARCHAR(24) NOT NULL,
    external_id VARCHAR(255),
    error_code VARCHAR(64) NOT NULL,
    error_message VARCHAR(1000) NOT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crawl_task_error_task
        FOREIGN KEY (crawl_task_id) REFERENCES crawl_task (id) ON DELETE CASCADE,
    CONSTRAINT ck_crawl_task_error_stage
        CHECK (stage IN ('FETCH', 'NORMALIZE', 'PERSIST', 'CLUSTER', 'SCORE'))
);

CREATE INDEX idx_crawl_task_error_task_occurred
    ON crawl_task_error (crawl_task_id, occurred_at);
