CREATE TABLE cluster_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_cluster_id BIGINT NOT NULL,
    analysis_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    schema_version VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    model_provider VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    result_payload JSONB,
    failure_code VARCHAR(64),
    failure_message VARCHAR(1000),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cluster_analysis_cluster
        FOREIGN KEY (hot_cluster_id) REFERENCES hot_cluster (id) ON DELETE CASCADE,
    CONSTRAINT ck_cluster_analysis_type
        CHECK (analysis_type IN ('CLUSTER_BRIEF')),
    CONSTRAINT ck_cluster_analysis_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_cluster_analysis_result_object
        CHECK (result_payload IS NULL OR jsonb_typeof(result_payload) = 'object'),
    CONSTRAINT ck_cluster_analysis_time_order
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX idx_cluster_analysis_cluster_created
    ON cluster_analysis (hot_cluster_id, created_at DESC, id DESC);

CREATE INDEX idx_cluster_analysis_status_created
    ON cluster_analysis (status, created_at DESC, id DESC);
