CREATE TABLE subscription_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    keywords JSONB NOT NULL DEFAULT '[]'::JSONB,
    source_types JSONB NOT NULL DEFAULT '[]'::JSONB,
    min_score NUMERIC(12, 4),
    suppress_window_hours INTEGER NOT NULL DEFAULT 24,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subscription_rule_name UNIQUE (name),
    CONSTRAINT ck_subscription_rule_keywords_array
        CHECK (jsonb_typeof(keywords) = 'array'),
    CONSTRAINT ck_subscription_rule_source_types_array
        CHECK (jsonb_typeof(source_types) = 'array'),
    CONSTRAINT ck_subscription_rule_min_score
        CHECK (min_score IS NULL OR min_score >= 0),
    CONSTRAINT ck_subscription_rule_suppress_window
        CHECK (suppress_window_hours >= 1)
);

CREATE INDEX idx_subscription_rule_enabled_created
    ON subscription_rule (enabled, created_at DESC, id DESC);

CREATE TABLE alert_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_rule_id BIGINT NOT NULL,
    hot_cluster_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'NEW',
    match_reason JSONB NOT NULL DEFAULT '{}'::JSONB,
    suppression_key CHAR(64) NOT NULL,
    matched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alert_record_subscription
        FOREIGN KEY (subscription_rule_id) REFERENCES subscription_rule (id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_record_cluster
        FOREIGN KEY (hot_cluster_id) REFERENCES hot_cluster (id) ON DELETE CASCADE,
    CONSTRAINT uq_alert_record_suppression_key UNIQUE (suppression_key),
    CONSTRAINT ck_alert_record_status
        CHECK (status IN ('NEW', 'ACKED', 'DISMISSED')),
    CONSTRAINT ck_alert_record_match_reason_object
        CHECK (jsonb_typeof(match_reason) = 'object')
);

CREATE INDEX idx_alert_record_subscription_status_matched
    ON alert_record (subscription_rule_id, status, matched_at DESC, id DESC);

CREATE INDEX idx_alert_record_cluster_matched
    ON alert_record (hot_cluster_id, matched_at DESC, id DESC);
