CREATE TABLE daily_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    status VARCHAR(24) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT NOT NULL,
    cluster_count INTEGER NOT NULL DEFAULT 0,
    top_cluster_ids JSONB NOT NULL DEFAULT '[]'::JSONB,
    content_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_daily_report_date UNIQUE (report_date),
    CONSTRAINT ck_daily_report_status
        CHECK (status IN ('GENERATED')),
    CONSTRAINT ck_daily_report_cluster_count
        CHECK (cluster_count >= 0),
    CONSTRAINT ck_daily_report_top_cluster_ids_array
        CHECK (jsonb_typeof(top_cluster_ids) = 'array'),
    CONSTRAINT ck_daily_report_content_payload_object
        CHECK (jsonb_typeof(content_payload) = 'object')
);

CREATE INDEX idx_daily_report_generated_at
    ON daily_report (generated_at DESC, id DESC);
