CREATE TABLE hot_item_signal_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_item_id BIGINT NOT NULL,
    raw_item_id BIGINT,
    source_type VARCHAR(32) NOT NULL,
    source_role VARCHAR(32) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    raw_metrics JSONB,
    normalized_signal JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_signal_snapshot_hot_item
        FOREIGN KEY (hot_item_id) REFERENCES hot_item (id) ON DELETE RESTRICT,
    CONSTRAINT fk_signal_snapshot_raw_item
        FOREIGN KEY (raw_item_id) REFERENCES raw_item (id) ON DELETE SET NULL,
    CONSTRAINT uq_signal_snapshot_raw_item
        UNIQUE (raw_item_id),
    CONSTRAINT ck_signal_snapshot_raw_metrics_object
        CHECK (raw_metrics IS NULL OR jsonb_typeof(raw_metrics) = 'object'),
    CONSTRAINT ck_signal_snapshot_normalized_signal_object
        CHECK (jsonb_typeof(normalized_signal) = 'object')
);

CREATE INDEX idx_signal_snapshot_hot_item_observed
    ON hot_item_signal_snapshot (hot_item_id, observed_at DESC);

