-- Phase 16: Event Cluster V2 support tables.
--
-- hot_item_feature stores the deterministic feature vector extracted from a
-- hot_item so the V2 clustering pipeline (ItemFeatureExtractor -> retriever ->
-- layered match rules) can run without re-deriving features on every match
-- attempt. One row per hot_item.
--
-- cluster_match_decision persists every ACCEPTED / REJECTED / REVIEW_REQUIRED /
-- NO_CANDIDATE decision the V2 strategy emits, alongside the candidate cluster
-- it considered and the structured match reason. V1 (hn-rule-v1) does not
-- write here; it keeps using hot_cluster_item for the same purpose.

CREATE TABLE hot_item_feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_item_id BIGINT NOT NULL,
    normalized_title TEXT NOT NULL,
    canonical_url TEXT,
    publisher_domain VARCHAR(255),
    event_time TIMESTAMPTZ,
    external_ids JSONB NOT NULL DEFAULT '{}'::JSONB,
    entities JSONB NOT NULL DEFAULT '[]'::JSONB,
    keywords JSONB NOT NULL DEFAULT '[]'::JSONB,
    event_type VARCHAR(64),
    feature_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hot_item_feature_item
        FOREIGN KEY (hot_item_id) REFERENCES hot_item (id) ON DELETE RESTRICT,
    CONSTRAINT uq_hot_item_feature_hot_item
        UNIQUE (hot_item_id),
    CONSTRAINT ck_hot_item_feature_external_ids_object
        CHECK (jsonb_typeof(external_ids) = 'object'),
    CONSTRAINT ck_hot_item_feature_entities_array
        CHECK (jsonb_typeof(entities) = 'array'),
    CONSTRAINT ck_hot_item_feature_keywords_array
        CHECK (jsonb_typeof(keywords) = 'array')
);

CREATE INDEX idx_hot_item_feature_event_time
    ON hot_item_feature (event_time DESC);

CREATE INDEX idx_hot_item_feature_entities_gin
    ON hot_item_feature USING GIN (entities);

CREATE INDEX idx_hot_item_feature_keywords_gin
    ON hot_item_feature USING GIN (keywords);

CREATE INDEX idx_hot_item_feature_canonical_url
    ON hot_item_feature (canonical_url);

CREATE TABLE cluster_match_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hot_item_id BIGINT NOT NULL,
    candidate_cluster_id BIGINT,
    decision VARCHAR(32) NOT NULL,
    match_score NUMERIC(8, 6),
    match_method VARCHAR(64),
    match_reason JSONB NOT NULL DEFAULT '{}'::JSONB,
    rule_version VARCHAR(64) NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_decision_hot_item
        FOREIGN KEY (hot_item_id) REFERENCES hot_item (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_decision_candidate_cluster
        FOREIGN KEY (candidate_cluster_id) REFERENCES hot_cluster (id) ON DELETE SET NULL,
    CONSTRAINT ck_match_decision_decision
        CHECK (decision IN ('ACCEPTED', 'REJECTED', 'REVIEW_REQUIRED', 'NO_CANDIDATE')),
    CONSTRAINT ck_match_decision_score
        CHECK (match_score IS NULL OR (match_score >= 0 AND match_score <= 1)),
    CONSTRAINT ck_match_decision_reason_object
        CHECK (jsonb_typeof(match_reason) = 'object')
);

CREATE INDEX idx_match_decision_hot_item_decided
    ON cluster_match_decision (hot_item_id, decided_at DESC);

CREATE INDEX idx_match_decision_candidate_cluster
    ON cluster_match_decision (candidate_cluster_id)
    WHERE candidate_cluster_id IS NOT NULL;

CREATE INDEX idx_match_decision_decision_rule
    ON cluster_match_decision (decision, rule_version);
